---
- name: Telnet to device to setup ssh
  hosts: telnet
  gather_facts: false
  connection: network_cli

  tasks:
    - name: telnet to device
      telnet:
        user: cisco
        password: cisco
        login_prompt: "Username: "
        prompts: 
          - "[>#]"
        command:
          - configure terminal
          - ssh server v2
          - commit
      register: output

    - debug:
        var: output.output

